### ISSUE TITLE
봇 만들기 시 취소 버튼이 있었으면 좋겠습니다.

### ISSUE THREAD

**Issue by edujason-hphk** [zzulu/codechatbot#14]
봇을 만들다가 저장하지 않고자 할 때 취소버튼이 없어 잠시 길을 잃었습니다.
취소 버튼을 만들어 사용자 경험을 높여주실 수 있을까요?

![Screen Shot 2020-07-07 at 16 53 07](https://user-images.githubusercontent.com/52459431/86741438-569a9f00-c072-11ea-96bd-dfad34860f69.png)

**Comment by zzulu** [comment]
좋은 의견 감사합니다! 추가해보겠습니다

**Comment by zzulu** [comment]
추가 완료하였습니다!

Resolved in 103f503, 5278886
